### ISSUE TITLE
Incomplete results for Zakarpattia Oblast and subareas, in Ukraine

### ISSUE THREAD

**Issue by erabrahams** [osm-search/Nominatim#2773]
## What did you search for?
Originally attempted to get all Oblast areas for Ukraine. All 26 Oblast areas except for 'Zakarpattia Oblast' returned areas on Nominatim. Zakarpattia returned only a centroid: 
https://nominatim.openstreetmap.org/ui/search.html?q=Zakarpattia+Oblast

To get around this, tried searching for Raions within Zakarpattia. Again, all worked except for one - Uzhhorod - which returned only the historical extent: 
https://nominatim.openstreetmap.org/ui/search.html?q=Uzhhorod+Raion

For completeness, then tried to go one level deeper and look for Hromadas in Uzhhorod Raion. "Uzhhorod Hromada", "Chop Hromada", and "Velykyi Bereznyi" returned areas, but "Kostrayna Hromada" returned only a centroid.

At this point I gave up, but did at least document which of the remaining Hromada areas could be successfully searched. All worked except "Kostryna Hromada", "Stavne Hromada", "Turi Remety", and "Dubrynychi":
https://nominatim.openstreetmap.org/ui/search.html?q=Kostryna+Hromada
https://nominatim.openstreetmap.org/ui/search.html?q=Stavne+Hromada
https://nominatim.openstreetmap.org/ui/search.html?q=Turi+Remety
https://nominatim.openstreetmap.org/ui/search.html?q=Dubrynychi

## What result did you get?
**Zakarpattia Oblast** - State centroid
**Uzhhrod Raion** - Historic area
**Kostryna Hromada** - Village centroid
**Stavene Hromada** - Village centroid
**Turi Remety** - Village centroid
**Dubrynychi** - Historic area

## What result did you expect?
**Zakarpattia Oblast** - Administrative area
**Uzhhrod Raion** - Administrative area
**Kostryna Hromada** - Administrative area
**Stavene Hromada** - Administrative area
**Turi Remety** - Administrative area
**Dubrynychi** - Administrative area

_**Links to existing Relations that should fulfill the search results:**_
**Zakarpattia Oblast** -https://www.openstreetmap.org/relation/72489
**Uzhhrod Raion** - https://www.openstreetmap.org/relation/11841375
**Kostryna Hromada** - https://www.openstreetmap.org/relation/12160091
**Stavene Hromada** - https://www.openstreetmap.org/relation/12160090
**Turi Remety** - https://www.openstreetmap.org/relation/11904894

_Potential Match_ - no English name provided, but location and Google translation of Ukrainian align (Dubrynytsk-Malobereznyansk rural community):
**Dubrynychi** - https://www.openstreetmap.org/relation/12159745

## Further details
No futher details, thanks for looking into this!

**Comment by lonvia** [comment]
This only affects stormfly-04 indicating that a way shared by all these relations was broken during reimport and fixed in the meantime. Fixed up manually on the server.

**Comment by erabrahams** [comment]
Just verified that Zakarpattia Oblast and Uzhhorod Raion are returning expected results on the site. Fanstastic! Thank you so much for your quick response.

Will note that the Hromadas noted still appear to only be returning Nodes, but for my purposes the Oblast fix is sufficient. Thanks again!

**Comment by lonvia** [comment]
The search issues for the hromedas are unrelated. The data is now there.

"Kostryna Hromada" has a full name "Kostryna Rural Hromada", so it only shows up when [searching for more results](https://nominatim.openstreetmap.org/ui/search.html?q=Kostryna+Hromada&exclude_place_ids=1393795).

"Stavene Hromada" is misspelled, it is [Stavne Hromeda](https://stormfly-04.openstreetmap.org/ui/search.html?q=Stavne+Hromada&exclude_place_ids=1396705%2C41770183%2C24431473) (same problem with 'rural'). Nominatim is rather unforgiving with spelling errors.

**Comment by erabrahams** [comment]
Understood, thanks for clearing those up!
